"use client";
import {useEffect,useRef,useState} from "react"; import {useParams,useRouter} from "next/navigation"; import Link from "next/link"; import {createClient} from "@/lib/supabase/client";
type PeerMap=Record<string,RTCPeerConnection>;
export default function VoiceRoomPage(){const s=createClient();const params=useParams<{id:string}>();const router=useRouter();const [uid,setUid]=useState("");const [room,setRoom]=useState<any>(null);const [members,setMembers]=useState<any[]>([]);const [muted,setMuted]=useState(false);const [joined,setJoined]=useState(false);const [err,setErr]=useState("");const channel=useRef<any>(null);const peers=useRef<PeerMap>({});const stream=useRef<MediaStream|null>(null);const audios=useRef<Record<string,HTMLAudioElement>>({});
async function start(){const {data:{user}}=await s.auth.getUser();if(!user){router.push("/login");return}setUid(user.id);const {data:r}=await s.from("rooms").select("id,name,allow_voice").eq("id",params.id).single();if(!r||!r.allow_voice){setErr("الصوت غير متاح في هذه الغرفة.");return}setRoom(r);const {data:m}=await s.from("room_members").select("user_id,profiles(display_name,username)").eq("room_id",params.id);setMembers(m||[]);try{stream.current=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});setJoined(true)}catch{setErr("اسمح للمتصفح بالوصول للميكروفون ثم جرّب مرة أخرى.");return}
const c=s.channel("voice-"+params.id,{config:{broadcast:{self:false}}});channel.current=c;
c.on("broadcast",{event:"signal"},async({payload}:any)=>{if(payload.to===user.id)await handleSignal(payload)});
c.on("broadcast",{event:"hello"},async({payload}:any)=>{if(payload.from!==user.id&&user.id<payload.from)await makeOffer(payload.from)});
c.subscribe(async(status:string)=>{if(status==="SUBSCRIBED")await c.send({type:"broadcast",event:"hello",payload:{from:user.id}})});
}
async function pcFor(peerId:string){if(peers.current[peerId])return peers.current[peerId];const pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});stream.current?.getTracks().forEach(t=>pc.addTrack(t,stream.current!));pc.onicecandidate=e=>{if(e.candidate)void channel.current?.send({type:"broadcast",event:"signal",payload:{from:uid,to:peerId,type:"ice",data:e.candidate}})};pc.ontrack=e=>{const a=audios.current[peerId]||new Audio();a.autoplay=true;a.srcObject=e.streams[0];audios.current[peerId]=a;void a.play().catch(()=>{})};peers.current[peerId]=pc;return pc}
async function makeOffer(peerId:string){const pc=await pcFor(peerId);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await channel.current?.send({type:"broadcast",event:"signal",payload:{from:uid,to:peerId,type:"offer",data:offer}})}
async function handleSignal(p:any){const pc=await pcFor(p.from);if(p.type==="offer"){await pc.setRemoteDescription(p.data);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await channel.current?.send({type:"broadcast",event:"signal",payload:{from:uid,to:p.from,type:"answer",data:answer}})}else if(p.type==="answer"){await pc.setRemoteDescription(p.data)}else if(p.type==="ice"){try{await pc.addIceCandidate(p.data)}catch{}}}
useEffect(()=>{void start();return()=>{stream.current?.getTracks().forEach(t=>t.stop());Object.values(peers.current).forEach(p=>p.close());if(channel.current)void s.removeChannel(channel.current)}},[params.id]);
function toggle(){stream.current?.getAudioTracks().forEach(t=>t.enabled=muted);setMuted(v=>!v)}
return <main className="min-h-screen p-5"><div className="mx-auto max-w-3xl"><Link href={"/rooms/"+params.id} className="text-sm text-white/50">← الغرفة</Link><section className="card mt-5 text-center"><div className="text-7xl">🎙️</div><h1 className="mt-4 text-3xl font-black">الغرفة الصوتية</h1><p className="mt-2 text-white/50">{room?.name||"..."}</p>{err&&<div className="mt-5 rounded-2xl bg-red-500/10 p-4 text-red-200">{err}</div>}<div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{members.map((m:any)=><div key={m.user_id} className={"rounded-2xl p-4 "+(m.user_id===uid?"bg-violet-600":"bg-white/5")}><div className="text-3xl">{m.user_id===uid&&!muted?"🎙️":"👤"}</div><div className="mt-2 truncate text-sm">{m.profiles?.display_name||"لاعب"}</div></div>)}</div><div className="mt-8 flex justify-center gap-3"><button disabled={!joined} onClick={toggle} className="rounded-2xl bg-violet-600 px-6 py-3 font-black">{muted?"🔇 فتح الميك":"🎙️ كتم الميك"}</button><button onClick={()=>router.push("/rooms/"+params.id)} className="rounded-2xl bg-red-600 px-6 py-3 font-black">مغادرة الصوت</button></div><p className="mt-4 text-xs text-white/35">WebRTC P2P + Supabase Realtime signaling، ومناسب للغرف الصغيرة.</p></section></div></main>