"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import AppNav from "@/components/AppNav";
export default function MessagesPage(){
 const s=createClient(); const [me,setMe]=useState(""); const [friends,setFriends]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [msgs,setMsgs]=useState<any[]>([]); const [body,setBody]=useState(""); const [err,setErr]=useState("");
 async function friendsLoad(uid:string){const {data}=await s.from("friend_requests").select("sender_id,receiver_id,status").eq("status","accepted").or("sender_id.eq."+uid+",receiver_id.eq."+uid);const ids=(data||[]).map((x:any)=>x.sender_id===uid?x.receiver_id:x.sender_id);if(!ids.length){setFriends([]);return}const {data:p}=await s.from("profiles").select("id,display_name,username").in("id",ids);setFriends(p||[])}
 async function messagesLoad(uid:string,other:string){const q=`and(sender_id.eq.${uid},receiver_id.eq.${other}),and(sender_id.eq.${other},receiver_id.eq.${uid})`;const {data,error}=await s.from("messages").select("id,sender_id,receiver_id,body,created_at").or(q).order("created_at");if(error)setErr(error.message);setMsgs(data||[])}
 useEffect(()=>{(async()=>{const {data:{user}}=await s.auth.getUser();if(!user)return;setMe(user.id);await friendsLoad(user.id)})()},[]);
 useEffect(()=>{if(!me||!selected)return;void messagesLoad(me,selected.id);const c=s.channel("dm-"+[me,selected.id].sort().join("-")).on("postgres_changes",{event:"*",schema:"public",table:"messages"},()=>void messagesLoad(me,selected.id)).subscribe();return()=>{void s.removeChannel(c)}},[me,selected?.id]);
 async function send(){if(!selected||!body.trim())return;const {error}=await s.rpc("send_direct_message",{p_receiver:selected.id,p_body:body.trim()});if(error)setErr(error.message);else setBody("");void messagesLoad(me,selected.id)}
 return <main className="min-h-screen p-5"><AppNav/><div className="mx-auto mt-5 grid max-w-6xl gap-4 lg:grid-cols-[280px_1fr]"><aside className="card"><h1 className="text-xl font-black">الأصدقاء</h1><div className="mt-4 space-y-2">{friends.map(f=><button key={f.id} onClick={()=>setSelected(f)} className={"w-full rounded-2xl p-3 text-right "+(selected?.id===f.id?"bg-violet-600":"bg-white/5")}><b>{f.display_name}</b><div className="text-xs opacity-60">@{f.username||"player"}</div></button>)}</div></aside><section className="card min-h-[65vh] flex flex-col">{selected?<><div className="border-b border-white/10 pb-4"><b>{selected.display_name}</b></div><div className="flex-1 space-y-2 overflow-y-auto py-4">{msgs.map(m=><div key={m.id} className={"flex "+(m.sender_id===me?"justify-end":"justify-start")}><div className={"max-w-[80%] rounded-2xl px-4 py-2 "+(m.sender_id===me?"bg-violet-600":"bg-white/10")}>{m.body}</div></div>)}</div><div className="flex gap-2"><input className="input" value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void send()} placeholder="اكتب رسالة..."/><button onClick={()=>void send()} className="rounded-2xl bg-violet-600 px-5 font-black">إرسال</button></div></>:<div className="grid flex-1 place-items-center text-white/40">اختار صديق وابدأ المحادثة 💬</div>}{err&&<p className="mt-3 text-sm text-red-300">{err}</p>}</section></div></main>
}