-- Production expansion migration. Applied to Supabase project tfpjsflmrkhvjmzmedfd.
-- Source-of-truth schema is kept here for reproducible deployments.
alter table public.profiles add column if not exists last_checkin_at timestamptz;
alter table public.rooms add column if not exists is_locked boolean not null default false, add column if not exists allow_voice boolean not null default true;
create table if not exists public.blocks (blocker_id uuid not null references public.profiles(id) on delete cascade, blocked_id uuid not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), primary key(blocker_id,blocked_id), check(blocker_id<>blocked_id));
create table if not exists public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid not null references public.profiles(id) on delete cascade, reported_user_id uuid references public.profiles(id) on delete cascade, room_id uuid references public.rooms(id) on delete cascade, message_id uuid references public.messages(id) on delete set null, reason text not null, details text not null default '', status text not null default 'open', created_at timestamptz not null default now(), resolved_at timestamptz);
create table if not exists public.account_settings (user_id uuid primary key references public.profiles(id) on delete cascade, language text not null default 'ar', push_notifications boolean not null default true, sound_notifications boolean not null default true, show_online boolean not null default true, allow_friend_requests boolean not null default true, allow_private_messages text not null default 'friends', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.player_stats (user_id uuid primary key references public.profiles(id) on delete cascade, games_played integer not null default 0, games_won integer not null default 0, games_lost integer not null default 0, total_score integer not null default 0, voice_minutes integer not null default 0, friends_count integer not null default 0, updated_at timestamptz not null default now());
create table if not exists public.cosmetics (id text primary key, kind text not null, name text not null, description text not null default '', price integer not null default 0, rarity text not null default 'common', asset_url text);
create table if not exists public.user_cosmetics (user_id uuid not null references public.profiles(id) on delete cascade, cosmetic_id text not null references public.cosmetics(id) on delete cascade, acquired_at timestamptz not null default now(), primary key(user_id,cosmetic_id));
create table if not exists public.daily_checkins (user_id uuid not null references public.profiles(id) on delete cascade, checkin_date date not null default current_date, day_number integer not null default 1, coins_awarded integer not null default 0, xp_awarded integer not null default 0, created_at timestamptz not null default now(), primary key(user_id,checkin_date));
create table if not exists public.game_results (id uuid primary key default gen_random_uuid(), session_id uuid references public.game_sessions(id) on delete set null, room_id uuid references public.rooms(id) on delete set null, game_type text not null, user_id uuid not null references public.profiles(id) on delete cascade, placement integer, score integer not null default 0, xp_awarded integer not null default 0, coins_awarded integer not null default 0, created_at timestamptz not null default now());
